# Generated by Django 4.2.8 on 2023-12-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
